# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GatewayHelper.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 221)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.vendorHorizontalLayout = QtWidgets.QHBoxLayout()
        self.vendorHorizontalLayout.setObjectName("vendorHorizontalLayout")
        self.vendorLabel = QtWidgets.QLabel(self.centralwidget)
        self.vendorLabel.setObjectName("vendorLabel")
        self.vendorHorizontalLayout.addWidget(self.vendorLabel)
        self.vendorLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.vendorLineEdit.setObjectName("vendorLineEdit")
        self.vendorHorizontalLayout.addWidget(self.vendorLineEdit)
        self.verticalLayout.addLayout(self.vendorHorizontalLayout)
        self.cartHorizontalLayout = QtWidgets.QHBoxLayout()
        self.cartHorizontalLayout.setObjectName("cartHorizontalLayout")
        self.cartLabel = QtWidgets.QLabel(self.centralwidget)
        self.cartLabel.setObjectName("cartLabel")
        self.cartHorizontalLayout.addWidget(self.cartLabel)
        self.cartLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.cartLineEdit.setObjectName("cartLineEdit")
        self.cartHorizontalLayout.addWidget(self.cartLineEdit)
        self.selectFileButton = QtWidgets.QPushButton(self.centralwidget)
        self.selectFileButton.setObjectName("selectFileButton")
        self.cartHorizontalLayout.addWidget(self.selectFileButton)
        self.verticalLayout.addLayout(self.cartHorizontalLayout)
        self.browserHorizontalLayout = QtWidgets.QHBoxLayout()
        self.browserHorizontalLayout.setObjectName("browserHorizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.browserHorizontalLayout.addItem(spacerItem)
        self.browserLabel = QtWidgets.QLabel(self.centralwidget)
        self.browserLabel.setObjectName("browserLabel")
        self.browserHorizontalLayout.addWidget(self.browserLabel)
        self.browserComboBox = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.browserComboBox.sizePolicy().hasHeightForWidth())
        self.browserComboBox.setSizePolicy(sizePolicy)
        self.browserComboBox.setMinimumSize(QtCore.QSize(200, 0))
        self.browserComboBox.setObjectName("browserComboBox")
        self.browserComboBox.addItem("")
        self.browserHorizontalLayout.addWidget(self.browserComboBox)
        self.verticalLayout.addLayout(self.browserHorizontalLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.runButton = QtWidgets.QPushButton(self.centralwidget)
        self.runButton.setObjectName("runButton")
        self.horizontalLayout.addWidget(self.runButton)
        self.cancelButton = QtWidgets.QPushButton(self.centralwidget)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout.addWidget(self.cancelButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.mainMenu = self.menuBar()
        self.fileMenu = self.mainMenu.addMenu('File')
        self.aboutAction = QtWidgets.QAction("About", self)
        self.fileMenu.addAction(self.aboutAction)
        # self.menubar = QtWidgets.QMenuBar(MainWindow)
        # self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        # self.menubar.setObjectName("menubar")
        # self.menuFile = QtWidgets.QMenu(self.menubar)
        # self.menuFile.setObjectName("menuFile")
        # self.menubar.addMenu(self.menuFile)
        # self.About = QtWidgets.QAction("About", MainWindow)
        # self.menuFile.addAction(self.About)
        # MainWindow.setMenuBar(self.menubar)
        # self.statusbar = QtWidgets.QStatusBar(MainWindow)
        # self.statusbar.setObjectName("statusbar")
        # MainWindow.setStatusBar(self.statusbar)
        # self.menubar.addAction(self.menuFile.menuAction())


        # Add signals and connections to class functions
        self.runButton.clicked.connect(self.run)
        self.cancelButton.clicked.connect(self.cancel)
        self.selectFileButton.clicked.connect(self.openFile)
        self.vendorLineEdit.textChanged.connect(self.updateVendor)
        self.aboutAction.triggered.connect(self.showAbout)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.vendorLabel.setText(_translate("MainWindow", "Vendor:"))
        self.vendorLineEdit.setPlaceholderText(_translate("MainWindow", "(Use exactly the title Gateway does)"))
        self.cartLabel.setText(_translate("MainWindow", "Cart Excel File:"))
        self.selectFileButton.setText(_translate("MainWindow", "Select File"))
        self.browserLabel.setText(_translate("MainWindow", "Browser"))
        self.browserComboBox.setItemText(0, _translate("MainWindow", "Chrome"))
        self.runButton.setText(_translate("MainWindow", "Run"))
        self.cancelButton.setText(_translate("MainWindow", "Cancel"))
        self.fileMenu.setTitle(_translate("MainWindow", " File"))

